#!/usr/bin/env python

from pyjacksm import libjack
from pyjacksm import state
import subprocess
from optparse import OptionParser
from ConfigParser import SafeConfigParser
import os
import time
import shutil

try:
    import dbus.service
    import gobject
    have_dbus = True
except:
    have_dbus = False


defaults = { "jackclientname": "sessionmanager", "sessiondir": "~/jackSessions", "templatedir": "~/.jackSession_templates" }

class SessionManager( object ):
    def __init__( self ):
        self.config = SafeConfigParser( defaults )
        self.config.read( os.path.expanduser( "~/.pyjacksmrc" ) )
        self.jackname = self.config.get( "DEFAULT", "jackclientname" )
        if self.config.has_section( "infra" ):
            self.infra_clients = {}
            for inf in self.config.items( "infra" ):
                self.infra_clients[inf[0]] = inf[1]
        else:
            self.infra_clients = { "a2j": "a2jmidid" }
        self.implicit_clients = [ "system" ]

        self.sessiondir = os.path.expanduser( self.config.get( "DEFAULT", "sessiondir" ) ) + "/" 
        if not os.path.exists( self.sessiondir ):
            print "Sessiondir %s does not exist. Creating it..."%self.sessiondir
            os.mkdir( self.sessiondir )

        self.templatedir = os.path.expanduser( self.config.get( "DEFAULT", "templatedir" ) ) + "/" 
        if not os.path.exists( self.templatedir ):
            print "Templatedir %s does not exist. Creating it..."%self.templatedir
            os.mkdir( self.templatedir )

	self.current_session = None

    def list_projects( self ):
        files = os.listdir( self.sessiondir )
        files = filter( lambda x: os.path.isdir( os.path.join( self.sessiondir, x ) ), files )
        return files

    def list_templates( self ):
        files = os.listdir( self.templatedir )
        files = filter( lambda x: os.path.isdir( os.path.join( self.templatedir, x ) ), files )
        return files

    def get_current_session( self ):
	if self.current_session:
	    return self.current_session
	else:
	    return ""

    def move_session( self, old, new ):
	shutil.move( os.path.join( self.sessiondir, old ), os.path.join( self.sessiondir, new ) )

    def rm_session( self, name ):
	shutil.rmtree( os.path.join( self.sessiondir, name ) )

    def session_exists( self, name ):
	return os.path.exists( self.sessiondir+name+"/session.xml" )

    def load_session( self, name, template=False ):
        if template:
            path = self.templatedir
        else:
            path = self.sessiondir

        if not os.path.exists( path+name+"/session.xml" ):
            print "Session %s does not exist"%name
            return -1

        self.cl = libjack.JackClient( self.jackname, True )

        sd = state.SessionDom( path+name+"/session.xml" )

        g=self.cl.get_graph()

        children = []

        for ic in sd.get_infra_clients():
            if not ic[0] in g.clients.keys():
                children.append( subprocess.Popen( ic[1], shell=True ) )


        print sd.get_client_names()

	if opt.renames:
	    g.ensure_clientnames( sd.get_reg_client_names() )
	    # get graph again... renaming isnt prefect yet.
	    g=self.cl.get_graph()

	# fixup names, doing this unconditionally, because
	# a client rename might have failed.
	sd.fixup_client_names( g )

	# now we have mangled all the names, lets reserve them.
	for (uuid, clientname) in sd.get_uuid_client_pairs():
	    print "reserving name %s"%clientname
	    g.reserve_name( uuid, clientname )

        # build up list of port connections
        conns = []
        for p in sd.get_port_names():
            for c in sd.get_connections_for_port( p ):
                conns.append( (p,c) )
        print conns

        # now fire up the processes
        for cname in sd.get_reg_client_names():
            cmd = sd.get_commandline_for_client( cname, path + name + "/" )
            children.append( subprocess.Popen( cmd, shell=True ) )

        avail_ports = g.get_port_list()
        # wait for ports to appear, and connect em.

        while len(conns) > 0:
            p = self.cl.port_queue.get()
            print p[0],p[1]
            pname = libjack.port_name(p[0])
            for c1 in conns:
                if c1[0]==pname:
                    if c1[1] in avail_ports:
                        self.cl.connect( pname, c1[1] )

                        conns.remove( c1 )
                        if (c1[1],c1[0]) in conns:
                            conns.remove( (c1[1],c1[0]) )

                    break

                if c1[1]==pname:
                    if c1[0] in avail_ports:
                        self.cl.connect( pname, c1[0] )

                        conns.remove( c1 )
                        if (c1[1],c1[0]) in conns:
                            conns.remove( (c1[1],c1[0]) )
                
                    break

            avail_ports.append( pname )
            

	self.cl.close()
        print "session restored..."
        return 0

    def quit_session( self, name ):
	return self.save_session( name, True )

    def save_template( self, name ):
        return self.save_session( name, False, True )

    def save_session( self, name, quit=False, template=False ): 
        if template:
            path = self.templatedir
        else:
            path = self.sessiondir

        if os.path.exists( path+name ):
            print "session %s already exists"%name
            return -1

        self.cl = libjack.JackClient( self.jackname, False )

        os.mkdir( self.sessiondir+name )
        g=self.cl.get_graph()
	if quit:
	    notify = self.cl.session_save_and_quit( path+name+"/" )
        elif template:
	    notify = self.cl.session_save_template( path+name+"/" )
	else:
	    notify = self.cl.session_save( path+name+"/" )

        for n in notify:
            c = g.get_client( n.clientname )
            c.set_commandline( n.commandline )
	    c.set_uuid( n.uuid )

        sd = state.SessionDom()

        for c in g.clients.values():
            if c.get_commandline() == "":
                if not c.name in self.infra_clients.keys()+self.implicit_clients:
                    g.remove_client( c.name )
                elif c.name in self.implicit_clients:
                    g.remove_client_only( c.name )
                else:
                    c.set_infra( self.infra_clients[c.name] )


        for i in g.clients.values():
            sd.add_client(i)

        f = file( path+name+"/session.xml", "w" )
        f.write( sd.get_xml() )
        f.close()

	self.cl.close()

        print sd.get_xml()
        return 0

if have_dbus:
    class DbusSM( dbus.service.Object ):
        def __init__( self, sm ):
            self.sm = sm
            dbus.service.Object.__init__( self, None, 
                    "/org/jackaudio/sessionmanager",
                    dbus.service.BusName( "org.jackaudio.sessionmanager", bus=dbus.SessionBus() ) )

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="s", out_signature="i" )
        def save_as( self, name ):
	    self.sm.current_session = name
            return self.sm.save_session( name )

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="s", out_signature="i" )
        def save_template( self, name ):
            return self.sm.save_template( name )

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="s", out_signature="i" )
        def save_over( self, name ):
	    self.sm.move_session( name, "jacksm-tmp-save" )
	    self.sm.current_session = name
            return self.sm.save_session( name )

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="", out_signature="i" )
        def save( self ):
	    if not self.sm.current_session:
		return -1

	    self.sm.move_session( self.sm.current_session, "jacksm-tmp-save" )
	    retval = self.sm.save_session( self.sm.current_session )
	    if retval:
		return retval

	    self.sm.rm_session( "jacksm-tmp-save" )
	    return retval

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="", out_signature="i" )
        def quit( self ):
	    if not self.sm.current_session:
		return -1

	    self.sm.move_session( self.sm.current_session, "jacksm-tmp-save" )
	    retval = self.sm.quit_session( self.sm.current_session )
	    if retval:
		return retval

	    self.sm.current_session = None
	    self.sm.rm_session( "jacksm-tmp-save" )
	    return retval

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="s", out_signature="i" )
        def quit_as( self, name ):
	    self.sm.current_session = None
            return self.sm.quit_session( name )

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="s", out_signature="i" )
        def load( self, name ):
	    if not self.sm.current_session:
		self.sm.current_session = name
	    else:
		self.sm.current_session = None

            return self.sm.load_session( name )

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="s", out_signature="i" )
        def load_template( self, name ):
            return self.sm.load_session( name, True )

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="", out_signature="as" )
        def list( self ):
            return self.sm.list_projects()

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="", out_signature="as" )
        def list_templates( self ):
            return self.sm.list_templates()

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="", out_signature="s" )
        def current_session( self ):
            return self.sm.get_current_session()

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="s", out_signature="b" )
        def session_exists( self, name ):
            return self.sm.session_exists( name )

        @dbus.service.method( dbus_interface="org.jackaudio.sessionmanager", in_signature="", out_signature="" )
        def daemon_quit( self ):
            loop.quit() 

oparser = OptionParser()
oparser.add_option( "--nodbus", action="store_false", dest="dbus", default=have_dbus,
                    help="Dont use DBUS to issue commands to a running instance" )
oparser.add_option( "--daemon", action="store_true", dest="daemon", default=False,
                    help="Start in daemon mode, and listen for dbus commands" )
oparser.add_option( "--save", action="store_true", dest="save", default=False,
                    help="Tell SessionManger to save." )
oparser.add_option( "--saveas", action="store", type="string", dest="saveas",
                    help="Save Session As <name>" )

oparser.add_option( "--quit", action="store_true", dest="quit", default=False,
                    help="Tell SessionManager to Save And Quit" )
oparser.add_option( "--current", action="store_true", dest="show_current", default=False,
                    help="show current session name" )

oparser.add_option( "--list", action="store_true", dest="list", default=False,
                    help="List Projects" )
oparser.add_option( "--quitdaemon", action="store_true", dest="quitdaemon", default=False,
                    help="Tell SessionManager Daemon to Exit" )
oparser.add_option( "--quitas", action="store", dest="quitas", type="string",
                    help="SaveAs And Quit" )
oparser.add_option( "--load", action="store", dest="load", type="string",
                    help="Load Session with <name>" )
oparser.add_option( "--renames", action="store_true", dest="renames", default=False,
                    help="Allow renaming offending clients" )

(opt,args) = oparser.parse_args()

if not opt.dbus:
    sm = SessionManager()
    try:
	if opt.saveas:
	    sm.save_session( opt.saveas )

	if opt.load:
	    sm.load_session( opt.load )

	if opt.quitas:
	    sm.quit_session( opt.quitas ) 
    except:
	sm.cl.close()
	raise
else:
    if opt.daemon:
	try:
	    sm = SessionManager()
	    from dbus.mainloop.glib import DBusGMainLoop
	    DBusGMainLoop(set_as_default=True)
	    dbsm = DbusSM( sm )
	    loop = gobject.MainLoop()
	    loop.run()
	except:
	    sm.cl.close()
	    raise
    else:
        session_bus = dbus.SessionBus()
        sm_proxy = session_bus.get_object( "org.jackaudio.sessionmanager", "/org/jackaudio/sessionmanager" )
        sm_iface = dbus.Interface( sm_proxy, "org.jackaudio.sessionmanager" )
        if opt.saveas:
            sm_iface.save_as( opt.saveas )
	if opt.save:
	    curr = sm_iface.current_session()
	    if curr:
		sm_iface.save()
	    else:
		print "No current project"

	if opt.quit:
	    curr = sm_iface.current_session()
	    if curr:
		sm_iface.quit()
	    else:
		print "No current project"

        if opt.quitas:
            sm_iface.quit_as( opt.quitas )
        if opt.load:
            sm_iface.load( opt.load )
        if opt.list:
            projects = sm_iface.list()
            for i in projects:
                print i

	if opt.show_current:
	    curr = sm_iface.current_session()
	    if curr:
		print curr
	    else:
		print "No Session"

        if opt.quitdaemon:
            sm_iface.daemon_quit()





